📂 # Extract data

In [1]:
import pandas as pd
import os
import numpy as np

In [2]:
data = 'https://raw.githubusercontent.com/alura-cursos/challenge2-data-science-LATAM/refs/heads/main/TelecomX_Data.json'

df_custumers = pd.read_json(data)

df_custumers

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
...,...,...,...,...,...,...
7262,9987-LUTYD,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
7263,9992-RRAMN,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
7264,9992-UJOEL,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
7265,9993-LHIEB,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Two year', 'PaperlessBilling': '..."
7266,9995-HOTOH,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'No', 'MultipleLines': 'No ph...","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Two year', 'PaperlessBilling': '..."

 🛠️ #Transformation

In [3]:
df_custumers.columns

Index(['customerID', 'Churn', 'customer', 'phone', 'internet', 'account'], dtype='object')

In [4]:
df_custumers.info ()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerID  7267 non-null   object
 1   Churn       7267 non-null   object
 2   customer    7267 non-null   object
 3   phone       7267 non-null   object
 4   internet    7267 non-null   object
 5   account     7267 non-null   object
dtypes: object(6)
memory usage: 340.8+ KB

In [5]:
# Normalization: flatten nested columns in df_custumers
df_custumers_norm = pd.concat([ #contac 
	df_custumers.drop(['customer', 'phone', 'internet', 'account'], axis=1),
	pd.json_normalize(df_custumers['customer']),
	pd.json_normalize(df_custumers['phone']),
	pd.json_normalize(df_custumers['internet']),
	pd.json_normalize(df_custumers['account'])
], axis=1)

In [6]:
df_custumers_norm

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,No,No,13,Yes,No,DSL,...,No,No,Yes,No,No,One year,No,Mailed check,55.15,742.9
7263,9992-RRAMN,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,...,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.7
7264,9992-UJOEL,No,Male,0,No,No,2,Yes,No,DSL,...,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75
7265,9993-LHIEB,No,Male,0,Yes,Yes,67,Yes,No,DSL,...,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65
7266,9995-HOTOH,No,Male,0,Yes,Yes,63,No,No phone service,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.6

In [7]:
#save raw data
output_dir_raw = '../data/raw'
file_path =os.path.join(output_dir_raw, 'custumers_norm.csv')
os.makedirs(output_dir_raw, exist_ok=True) 
df_custumers_norm.to_csv(file_path, index=False)

In [8]:
df_custumers_norm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7267 non-null   object
 1   Churn             7267 non-null   object
 2   gender            7267 non-null   object
 3   SeniorCitizen     7267 non-null   int64
 4   Partner           7267 non-null   object
 5   Dependents        7267 non-null   object
 6   tenure            7267 non-null   int64
 7   PhoneService      7267 non-null   object
 8   MultipleLines     7267 non-null   object
 9   InternetService   7267 non-null   object
 10  OnlineSecurity    7267 non-null   object
 11  OnlineBackup      7267 non-null   object
 12  DeviceProtection  7267 non-null   object
 13  TechSupport       7267 non-null   object
 14  StreamingTV       7267 non-null   object
 15  StreamingMovies   7267 non-null   object
 16  Contract          7267 non-null   object
 17  PaperlessBilling  7267 non-null   object
 18  PaymentMethod     7267 non-null   object
 19  Charges.Monthly   7267 non-null   float64
 20  Charges.Total     7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

In [9]:
df_custumers_norm.shape

(7267, 21)

In [10]:
df_custumers_norm.isnull().sum()

customerID          0
Churn               0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
Charges.Monthly     0
Charges.Total       0
dtype: int64

In [11]:
df_custumers_norm.duplicated().sum()

0

In [17]:
pd.unique(pd.Series(df_custumers_norm['customerID']))

array(['0002-ORFBO', '0003-MKNFE', '0004-TLHLJ', ..., '9992-UJOEL',
       '9993-LHIEB', '9995-HOTOH'], dtype=object)

In [15]:
df_custumers_norm.columns

Index(['customerID', 'Churn', 'gender', 'SeniorCitizen', 'Partner',
       'Dependents', 'tenure', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod', 'Charges.Monthly',
       'Charges.Total'],
      dtype='object')

In [ ]:
# Check for outliers in numeric columns (example: Charges.Monthly, Charges.Total)

numeric_columns = df_custumers_norm.select_dtypes(include=['float64', 'int64']).columns
print(df_custumers_norm[numeric_columns].describe())

       SeniorCitizen       tenure  Charges.Monthly
count    7267.000000  7267.000000      7267.000000
mean        0.162653    32.346498        64.720098
std         0.369074    24.571773        30.129572
min         0.000000     0.000000        18.250000
25%         0.000000     9.000000        35.425000
50%         0.000000    29.000000        70.300000
75%         0.000000    55.000000        89.875000
max         1.000000    72.000000       118.750000

In [19]:
# Check categorical columns for inconsistencies
# We check the unique values in categorical columns to spot any potential inconsistencies
print("\nCategorical Columns Check (Unique Values):")
categorical_columns = df_custumers_norm.select_dtypes(include=['object']).columns
for col in categorical_columns:
    print(f"{col}: {df_custumers_norm[col].unique()}")

Categorical Columns Check (Unique Values):
customerID: ['0002-ORFBO' '0003-MKNFE' '0004-TLHLJ' ... '9992-UJOEL' '9993-LHIEB'
 '9995-HOTOH']
Churn: ['No' 'Yes' '']
gender: ['Female' 'Male']
Partner: ['Yes' 'No']
Dependents: ['Yes' 'No']
PhoneService: ['Yes' 'No']
MultipleLines: ['No' 'Yes' 'No phone service']
InternetService: ['DSL' 'Fiber optic' 'No']
OnlineSecurity: ['No' 'Yes' 'No internet service']
OnlineBackup: ['Yes' 'No' 'No internet service']
DeviceProtection: ['No' 'Yes' 'No internet service']
TechSupport: ['Yes' 'No' 'No internet service']
StreamingTV: ['Yes' 'No' 'No internet service']
StreamingMovies: ['No' 'Yes' 'No internet service']
Contract: ['One year' 'Month-to-month' 'Two year']
PaperlessBilling: ['Yes' 'No']
PaymentMethod: ['Mailed check' 'Electronic check' 'Credit card (automatic)'
 'Bank transfer (automatic)']
Charges.Total: ['593.3' '542.4' '280.85' ... '742.9' '4627.65' '3707.6']

In [20]:
# Check for consistency in categorical variables (e.g., 'gender', 'SeniorCitizen', 'Partner', etc.)
# Some variables should have only a limited set of values. Let's check if they match expectations
print("\nChecking Consistency in Categorical Variables:")
expected_values = {
    'gender': ['Male', 'Female'],
    'SeniorCitizen': [0, 1],  # Assuming SeniorCitizen is binary (0 or 1)
    'Partner': ['Yes', 'No'],
    'Dependents': ['Yes', 'No'],
    'PhoneService': ['Yes', 'No'],
    'MultipleLines': ['Yes', 'No', 'No phone service'],
    'InternetService': ['DSL', 'Fiber optic', 'No'],
    'OnlineSecurity': ['Yes', 'No', 'No internet service'],
    'OnlineBackup': ['Yes', 'No', 'No internet service'],
    'DeviceProtection': ['Yes', 'No', 'No internet service'],
    'TechSupport': ['Yes', 'No', 'No internet service'],
    'StreamingTV': ['Yes', 'No', 'No internet service'],
    'StreamingMovies': ['Yes', 'No', 'No internet service'],
    'Contract': ['Month-to-month', 'One year', 'Two year'],
    'PaperlessBilling': ['Yes', 'No'],
    'PaymentMethod': ['Electronic check', 'Mailed check', 'Bank transfer (automatic)', 'Credit card (automatic)'],
}

Checking Consistency in Categorical Variables:

In [21]:
# Check for any unexpected values in the categorical columns
for col, expected in expected_values.items():
    unique_vals = df_custumers_norm[col].unique()
    invalid_vals = set(unique_vals) - set(expected)
    if invalid_vals:
        print(f"Invalid values in {col}: {invalid_vals}")
    else:
        print(f"All values in {col} are valid.")

All values in gender are valid.
All values in SeniorCitizen are valid.
All values in Partner are valid.
All values in Dependents are valid.
All values in PhoneService are valid.
All values in MultipleLines are valid.
All values in InternetService are valid.
All values in OnlineSecurity are valid.
All values in OnlineBackup are valid.
All values in DeviceProtection are valid.
All values in TechSupport are valid.
All values in StreamingTV are valid.
All values in StreamingMovies are valid.
All values in Contract are valid.
All values in PaperlessBilling are valid.
All values in PaymentMethod are valid.

#### Diccionario de datos

- `customerID`: número de identificación único de cada cliente 🟢
- `Churn`: si el cliente dejó o no la empresa 🔴
- `gender`: género (masculino y femenino) 🟢
- `SeniorCitizen`: información sobre si un cliente tiene o no una edad igual o mayor a 65 años 🟢
- `Partner`: si el cliente tiene o no una pareja
- `Dependents`: si el cliente tiene o no dependientes
- `tenure`: meses de contrato del cliente
- `PhoneService`: suscripción al servicio telefónico
- `MultipleLines`: suscripción a más de una línea telefónica 🟢
- `InternetService`: suscripción a un proveedor de internet 🟢
- `OnlineSecurity`: suscripción adicional de seguridad en línea 
- `OnlineBackup`: suscripción adicional de respaldo en línea 
- `DeviceProtection`: suscripción adicional de protección del dispositivo 
- `TechSupport`: suscripción adicional de soporte técnico, menor tiempo de espera 🟢
- `StreamingTV`: suscripción de televisión por cable
- `StreamingMovies`: suscripción de streaming de películas
- `Contract`: tipo de contrato 🟢
- `PaperlessBilling`: si el cliente prefiere recibir la factura en línea
- `PaymentMethod`: forma de pago
- `Charges.Monthly`: total de todos los servicios del cliente por mes 🟢
- `Charges.Total`: total gastado por el cliente 🟢

In [22]:
# Handling Missing Values
# If there are any missing values, we can handle them by either filling them with the mean/median (for numerical columns)
# or the most frequent value (for categorical columns). Alternatively, you can drop rows with missing data if needed.

print("\nHandling Missing Values:")

# Fill missing numerical columns with the median value (common approach for skewed data)
numerical_columns = df_custumers_norm.select_dtypes(include=['float64', 'int64']).columns
for col in numerical_columns:
    median_value = df_custumers_norm[col].median()
    df_custumers_norm[col].fillna(median_value, inplace=True)

# Fill missing categorical columns with the most frequent value (mode)
categorical_columns = df_custumers_norm.select_dtypes(include=['object']).columns
for col in categorical_columns:
    mode_value = df_custumers_norm[col].mode()[0]
    df_custumers_norm[col].fillna(mode_value, inplace=True)

print("Missing values handled.")

# Handling Duplicates
# We will drop the duplicate rows to ensure we only have unique entries.
print("\nHandling Duplicates:")

Handling Missing Values:
Missing values handled.

Handling Duplicates:

C:\Users\zaire\AppData\Local\Temp\ipykernel_5072\3811159209.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_custumers_norm[col].fillna(median_value, inplace=True)
C:\Users\zaire\AppData\Local\Temp\ipykernel_5072\3811159209.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_custumers_norm[col].fillna(mode_value, inplace=True)

In [23]:
df_custumers_norm.drop_duplicates(inplace=True)

print("Duplicates removed.")

Duplicates removed.

In [24]:
# Fixing Inconsistencies in Categorical Columns
# Some categorical variables may have invalid values or unexpected entries.
# We will replace those values with the valid ones, or drop rows that contain invalid values.

print("\nFixing Inconsistencies in Categorical Columns:")

# Expected values for categorical columns, as per the earlier check
expected_values = {
    'gender': ['Male', 'Female'],
    'SeniorCitizen': [0, 1],
    'Partner': ['Yes', 'No'],
    'Dependents': ['Yes', 'No'],
    'PhoneService': ['Yes', 'No'],
    'MultipleLines': ['Yes', 'No', 'No phone service'],
    'InternetService': ['DSL', 'Fiber optic', 'No'],
    'OnlineSecurity': ['Yes', 'No', 'No internet service'],
    'OnlineBackup': ['Yes', 'No', 'No internet service'],
    'DeviceProtection': ['Yes', 'No', 'No internet service'],
    'TechSupport': ['Yes', 'No', 'No internet service'],
    'StreamingTV': ['Yes', 'No', 'No internet service'],
    'StreamingMovies': ['Yes', 'No', 'No internet service'],
    'Contract': ['Month-to-month', 'One year', 'Two year'],
    'PaperlessBilling': ['Yes', 'No'],
    'PaymentMethod': ['Electronic check', 'Mailed check', 'Bank transfer (automatic)', 'Credit card (automatic)'],
}

# Loop through the columns and fix any invalid values
for col, valid_values in expected_values.items():
    # Replace invalid values with the most frequent (mode) valid value
    df_custumers_norm[col] = df_custumers_norm[col].apply(lambda x: x if x in valid_values else df_custumers_norm[col].mode()[0])

print("Inconsistencies in categorical columns fixed.")

# Handling Data Types
# Ensure that each column has the correct data type.
# We will convert 'SeniorCitizen' and 'Churn' to categorical values for consistency if they are not already.
print("\nHandling Data Types:")

Fixing Inconsistencies in Categorical Columns:
Inconsistencies in categorical columns fixed.

Handling Data Types:

In [26]:
# Convert 'SeniorCitizen' and 'Churn' to categorical
df_custumers_norm['SeniorCitizen'] = df_custumers_norm['SeniorCitizen'].astype('category')
df_custumers_norm['Churn'] = df_custumers_norm['Churn'].astype('category')

In [27]:
# Handle invalid values before converting to float
print("\nCleaning 'Charges.Total' column:")

# Replace non-numeric values (e.g., empty strings, or other invalid entries) with NaN
df_custumers_norm['Charges.Total'] = pd.to_numeric(df_custumers_norm['Charges.Total'], errors='coerce')

# Optionally, you can fill NaN values in 'Charges.Total' with the median or another value
df_custumers_norm['Charges.Total'].fillna(df_custumers_norm['Charges.Total'].median(), inplace=True)

# Now safely convert to float
df_custumers_norm['Charges.Total'] = df_custumers_norm['Charges.Total'].astype(float)

print("'Charges.Total' column cleaned and converted to float.")

# Proceed with the rest of the process
# Convert 'Charges.Monthly' to float if it hasn't been handled yet
df_custumers_norm['Charges.Monthly'] = pd.to_numeric(df_custumers_norm['Charges.Monthly'], errors='coerce')
df_custumers_norm['Charges.Monthly'].fillna(df_custumers_norm['Charges.Monthly'].median(), inplace=True)
df_custumers_norm['Charges.Monthly'] = df_custumers_norm['Charges.Monthly'].astype(float)

print("Both 'Charges.Monthly' and 'Charges.Total' columns are now cleaned and converted to float.")

Cleaning 'Charges.Total' column:
'Charges.Total' column cleaned and converted to float.
Both 'Charges.Monthly' and 'Charges.Total' columns are now cleaned and converted to float.

C:\Users\zaire\AppData\Local\Temp\ipykernel_5072\1264648824.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_custumers_norm['Charges.Total'].fillna(df_custumers_norm['Charges.Total'].median(), inplace=True)
C:\Users\zaire\AppData\Local\Temp\ipykernel_5072\1264648824.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_custumers_norm['Charges.Monthly'].fillna(df_custumers_norm['Charges.Monthly'].median(), inplace=True)

In [28]:
# Final Check (Optional but recommended)
# After handling missing values, duplicates, and inconsistencies, it's always good to perform a final check.
print("\nFinal Check:")
print(df_custumers_norm.info())  # This will show the data types and non-null counts
print("\nUnique Values in Categorical Columns:")
for col in categorical_columns:
    print(f"{col}: {df_custumers_norm[col].unique()}")

Final Check:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7267 non-null   object
 1   Churn             7267 non-null   category
 2   gender            7267 non-null   object
 3   SeniorCitizen     7267 non-null   category
 4   Partner           7267 non-null   object
 5   Dependents        7267 non-null   object
 6   tenure            7267 non-null   int64
 7   PhoneService      7267 non-null   object
 8   MultipleLines     7267 non-null   object
 9   InternetService   7267 non-null   object
 10  OnlineSecurity    7267 non-null   object
 11  OnlineBackup      7267 non-null   object
 12  DeviceProtection  7267 non-null   object
 13  TechSupport       7267 non-null   object
 14  StreamingTV       7267 non-null   object
 15  StreamingMovies   7267 non-null   object
 16  Contract          7267 non-null   object
 17  PaperlessBilling  7267 non-null   object
 18  PaymentMethod     7267 non-null   object
 19  Charges.Monthly   7267 non-null   float64
 20  Charges.Total     7267 non-null   float64
dtypes: category(2), float64(2), int64(1), object(16)
memory usage: 1.1+ MB
None

Unique Values in Categorical Columns:
customerID: ['0002-ORFBO' '0003-MKNFE' '0004-TLHLJ' ... '9992-UJOEL' '9993-LHIEB'
 '9995-HOTOH']
Churn: ['No', 'Yes', '']
Categories (3, object): ['', 'No', 'Yes']
gender: ['Female' 'Male']
Partner: ['Yes' 'No']
Dependents: ['Yes' 'No']
PhoneService: ['Yes' 'No']
MultipleLines: ['No' 'Yes' 'No phone service']
InternetService: ['DSL' 'Fiber optic' 'No']
OnlineSecurity: ['No' 'Yes' 'No internet service']
OnlineBackup: ['Yes' 'No' 'No internet service']
DeviceProtection: ['No' 'Yes' 'No internet service']
TechSupport: ['Yes' 'No' 'No internet service']
StreamingTV: ['Yes' 'No' 'No internet service']
StreamingMovies: ['No' 'Yes' 'No internet service']
Contract: ['One year' 'Month-to-month' 'Two year']
PaperlessBilling: ['Yes' 'No']
PaymentMethod: ['Mailed check' 'Electronic check' 'Credit card (automatic)'
 'Bank transfer (automatic)']
Charges.Total: [ 593.3   542.4   280.85 ...  742.9  4627.65 3707.6 ]

In [30]:
df_custumers_norm

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.30
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.40
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,No,No,13,Yes,No,DSL,...,No,No,Yes,No,No,One year,No,Mailed check,55.15,742.90
7263,9992-RRAMN,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,...,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.70
7264,9992-UJOEL,No,Male,0,No,No,2,Yes,No,DSL,...,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75
7265,9993-LHIEB,No,Male,0,Yes,Yes,67,Yes,No,DSL,...,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65
7266,9995-HOTOH,No,Male,0,Yes,Yes,63,No,No phone service,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.60